### ISSUE TITLE
👿 docker-compose up failed

### ISSUE THREAD

**Issue by jaynamm** [jaynamm/hadoop-cluster#2]
### 도커 컴포즈 실패
도커 컴포즈를 통해 컨테이너를 실행하려고 하니 다음과 같이 바로 종료되었다.  
아마도 문제는 도커 컴포즈로 컨테이너를 동시에 띄우는 과정에서 무슨 설정에 문제가 있는게 아닐까 싶은데...
내가 도커 컴포즈에 대한 이해가 부족하다보니 조금 더 알아보고 이해하는 시간이 필요해보인다.

### docker-compose 실행 결과
```
$ docker-compose up
[+] Running 4/0
 ✔ Container dn1  Created                                                                                                                             0.1s 
 ✔ Container nn   Created                                                                                                                             0.1s 
 ✔ Container dn2  Created                                                                                                                             0.1s 
 ✔ Container dn3  Created                                                                                                                             0.1s 
Attaching to dn1, dn2, dn3, nn
dn2 exited with code 0
dn1 exited with code 0
dn3 exited with code 0
nn exited with code 0
```

### docker-compose.yaml
도커 컴포즈 파일은 다음과 같다.  

```
version: '3.8'

services:
  nn:
    image: hadoop-base:latest
    container_name: nn
    hostname: nn
    restart: always
    ports:
      - 50070:50070
      - 9000:9000
    entrypoint: /opt/hadoop/entrypoint.sh
    networks:
      - bridge

  dn1:
    image: hadoop-base:latest
    container_name: dn1
    hostname: dn1
    entrypoint: /opt/hadoop/entrypoint.sh
    networks:
      - bridge

  dn2:
    image: hadoop-base:latest
    container_name: dn2
    hostname: dn2
    entrypoint: /opt/hadoop/entrypoint.sh
    networks:
      - bridge

  dn3:
    image: hadoop-base:latest
    container_name: dn3
    hostname: dn3
    entrypoint: /opt/hadoop/entrypoint.sh
    networks:
      - bridge


networks:
  bridge:
```
